export const styles = {
  container: {
    width: 800,
    height: 'auto',
    maxWidth: 400,
    margin: '40px auto',
    padding: 24,
    border: '1px solid #ddd',
    borderRadius: 16,
    background: '#FAFAFA',
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontWeight: 'bold',
    fontSize: 18,
  },
  menuIcon: {
    fontSize: 22,
    cursor: 'pointer',
  },
  backBtn: {
    fontSize: 18,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
  },
recipeCard: {
  backgroundColor: '#fff',
  padding: '15px',
  marginBottom: '10px',
  borderRadius: '12px',
  boxShadow: '0 2px 8px rgba(0,0,0,0.1)'
},


  button: {
    width: '100%',
    padding: '32px 0',
    fontSize: 20,
    background: '#EAEAEA',
    border: '1px solid #ccc',
    borderRadius: 8,
    marginBottom: 8,
    cursor: 'pointer',
  },
  input: {
    flex: 1,
    padding: 8,
    fontSize: 16,
    borderRadius: 4,
    border: '1px solid #ccc',
  },
  photoBtn: {
    padding: '8px 16px',
    fontSize: 16,
    background: '#ccc',
    border: 'none',
    borderRadius: 4,
    cursor: 'pointer',
  },
  ingredientBox: {
    minHeight: 100,
    border: '1px solid #ccc',
    borderRadius: 8,
    padding: 12,
    background: '#fff',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  ingredientItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 16,
  },
  removeBtn: {
    background: 'none',
    border: 'none',
    color: '#e00',
    fontSize: 18,
    cursor: 'pointer',
  },
  addBtn: {
    marginTop: 8,
    padding: '8px 0',
    width: '100%',
    background: '#4CAF50',
    color: '#fff',
    border: 'none',
    borderRadius: 4,
    fontSize: 16,
    cursor: 'pointer',
  },
  recipeCard: {
    display: 'flex',
    gap: 12,
    border: '1px solid #ccc',
    borderRadius: 8,
    padding: 12,
    background: '#fff',
    alignItems: 'center',
  },
  recipeImage: {
    width: 60,
    height: 60,
    objectFit: 'cover',
    borderRadius: 8,
  },
};